### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by mbenitez01** [ejeklint/ArduinoWebsocketServer#15]
using the library, Iget this error:

"invalid conversion from 'byte*' to 'int'

at this point of code

byte mac[] = {0xDE, 0xAD, 0xBE, 0xEF, 0xFE, 0xED };
byte ip[] = { 192, 168, 1 , 200 };	// IP Address of the Arduino.
WebSerial mySerial(mac, ip); // Initialises WebSerial with mac and ip.

**Comment by ejeklint** [comment]
Reopen if still an issue.
