### ISSUE TITLE
ESP8266

### ISSUE THREAD

**Issue by rahul2704** [ejeklint/ArduinoWebsocketServer#20]
hey there. Nice project. I would like to run a web server on the esp8266, programmed using arduino. How can I implement your code to maybe turn a LED on/off from a web app? is this possible?

**Comment by danieloneill** [comment]
Hi there,

Unfortunately this library is "hardcoded" for use with Ethernet (or UIPEthernet with a minor code change) and would require some work to modify for use with most any ESP8266 library.

However there is a library specifically written for adding websocket capability to an esp8266: https://github.com/Links2004/arduinoWebSockets

I'd recommend trying that first and if it doesn't pan out we can try something else.

**Comment by rahul2704** [comment]
Hi. Thank you for taking the time to reply me. I was really helpful. But can you clarify somethings for me?
1. Does the link you provided use the esp8266 as standalone ?
2. Does it setup an access point and allow another smartphone running client to connect to it?
I want to use it for a project whereby a web app sends values from smartphone to esp8266. Is this possible? Thanks again for your support

**Comment by danieloneill** [comment]
I'm not involved with that project nor have I used it, you'd have to ask over there.

**Comment by ejeklint** [comment]
Hi @rahul2704 sorry for delayed answer. I'm not maintaining this any longer due to lack of time. As noted by @danieloneill the library is rather limited and does not support ESP8266 library. Feel free to fork the project if you want continue develop it.

**Comment by rahul2704** [comment]
thank you
